#server:
#  port: 8789

#management:
#  port: 8990

info:
  component: turbine
  
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: WARN
    
#turbine:
 #aggregator:
 #clusterNameExpression: new String("default")
 #appConfig: product-service, product-inventory-service
#turbine.InstanceMonitor.eventStream.skipLineLogic.enabled: false
#turbine.instanceInsertPort.default: false
#turbine.combineHostPort: true


spring.rabbitmq:
  host: localhost
  port: 15672